/*
 *  Script generated by LS Script Generator, v.TK.0
 *
 *  For download info, please visit:
 *  http://nwvault.ign.com/View.php?view=Other.Detail&id=1502
 */
// Put this script OnOpen.

  void main()
{


    DelayCommand(10.0, ActionCloseDoor(OBJECT_SELF));   ;
    DelayCommand(1.0, SetLocked(OBJECT_SELF, TRUE));

}

